name: pokemon_go
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.0.1
  dio: ^5.1.2
  cached_network_image: ^3.2.3
  hooks_riverpod: ^2.3.8
  flutter_hooks: ^0.20.0
  riverpod_annotation: ^2.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  go_router: ^12.1.1
  gap: ^3.0.1
  package_info_plus: ^4.1.0
  sliver_tools: ^0.2.12
  flutter_spinkit: ^5.2.0
  dartz: ^0.10.1
  flutter_cache_manager: ^3.3.1
  flex_color_scheme: ^7.2.0
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: ^7.0.1
  build_runner: ^2.4.2
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  mockito: ^5.3.2
  riverpod_generator: ^2.2.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/